[project]
name = "streamlit-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "nodriver>=0.48.1",
    "streamlit>=1.52.2",
    "undetected-chromedriver>=3.5.5",
    "zendriver>=0.15.2",
]
